# Generated by Django 5.2.11 on 2026-03-06 22:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consumption', '0001_initial'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='consumo',
            name='cliente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='consumos', to='users.cliente'),
        ),
        migrations.DeleteModel(
            name='Cliente',
        ),
    ]
